{
  blogs {
    _id
    title
    short_text
    imageURL
    likes {
      _id
      first_name
      last_name
    }
    dislikes {
      _id
      first_name
      last_name
    }
    comments {
      _id
      comment
      openToComment
      createdAt
      user {
        _id
        first_name
        last_name
      }
      answers {
        _id
        comment
        createdAt
        user {
          _id
          first_name
          last_name
        }
      }
    }
    author {
      _id
      first_name
      last_name
    }
    category {
      _id
      title
    }
  }
}
