{
  courses {
    _id
    title
    short_text
    image
    imageURL
    tags
        comments {
      _id
      comment
      openToComment
      createdAt
      user {
        _id
        first_name
        last_name
      }
      answers {
        _id
        comment
        createdAt
        user {
          _id
          first_name
          last_name
        }
      }
    }
    category {
      _id
      title
    }
    price
    discount
    count
    type
    status
    teacher {
      _id
      first_name
      last_name
    }
    chapters {
      _id
      title
      text
      episodes {
        _id
        title
        text
        type
        time
        videoAddress
        videoURL
      }
    }
  }
}
