{
  products {
    _id
    title
    text
    short_text
    images
    imagesURL
    tags
    comments {
      _id
      comment
      openToComment
      createdAt
      answers {
        _id
        comment
        user {
          first_name
          last_name
        }
        createdAt
      }
      user {
        first_name
        last_name
      }
    }
    category {
      _id
      title
    }
    price
    discount
    count
    type
    supplier {
      first_name
      last_name
    }
    features {
      length
      height
      width
      weight
      colors
      madein
    }
  }
}
